### ISSUE TITLE
Can't use import function

### ISSUE THREAD

**Issue by Shirobaka** [chocolatkey/FoOlSlide2#16]
Hey,
i can't use the import function for new chapters, i tried it on different machines, reinstalled FoOlSlide2 and checked my apache error logs, i found nothing.

My system:
Debian GNU/Linux 8.9 (jessie)
FoOlSlide2 Version: 2.3.3
PHP-Version: 5.6.31-4+0\~20170804100521.6+jessie~1.gbpea630b

Server Information
------------------------------
Web Server Software = Apache
PHP Version = 5.6.31-4+0\~20170804100521.6+jessie~1.gbpea630b

Software Information
------------------------------
FoOlSlide Version = 2.3.3
Environment = Production

PHP Configuration
------------------------------
php.ini Location = /etc/php/5.6/fpm/php.ini
Safe Mode = Aus
Allow URL fopen = Ein
Max Execution Time = 180
File Uploads = Eingeschaltet
Max POST Size = 512M
Max Upload Size = 128M
Max File Uploads = 128

Extensions
------------------------------
cURL = Installiert
GD2 = Installiert

Report Generated: Tue, 08 Aug 17 15:03:12 +0200

Anyone know the issue?

**Comment by chocolatkey** [comment]
Have you checked if all folder permissions are properly set?

**Comment by Diablofan** [comment]
I was having issues with the import page as well, my issue (which I don't know if it is the same as yours) is that the section for the chapters to import wouldn't load. After poking at the view code, since the JS showed everything was generating fine, showed that [this line here](https://github.com/chocolatkey/FoOlSlide2/blob/master/application/views/admin/series/import_compressed_list.php#L28) was the problem. I swapped it out for `result += '<input type="hidden" name="input_language" value="en-us" />';` and the import page started working as expected again. I only hard coded the language because its the only language I'm using on my instance of it.

**Comment by Shirobaka** [comment]
Yea, that works fine, thanks for your help!
@chocolatkey Sorry i haven't answered, i haven't recieved an email for your reply so i forget about it... My folder permissions are properly setted.

**Comment by Diablofan** [comment]
@Shirobaka Glad that fixed the issue for ya. 

@chocolatkey I know you're working on FoolSlideX, so feel free to close the issue since we found a work around.

**Comment by chocolatkey** [comment]
@Diablofan I will, thanks for the support
