### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by prophetnite** [chocolatkey/FoOlSlide2#8]
Loading /install page sits for awhile, then 'Too many redirects'.  Server running Nginx with php5-fpm.  I played with my server block config but have gotten no other results.  Any known compatibility issues or anything I should check? I would love to get this running.

**Comment by chocolatkey** [comment]
It's caused by the new force https option I've been setting by default, which I have run in to issues with on nginx. I'm going to remove it in the next build and instead warn people when they are accessing the admin panel while using http. For now do the following:
Down near the bottom of application/config/constants.php edit

``` php
define('FORCE_SSL', true);
```

to false

**Comment by prophetnite** [comment]
Works fine.  
I thought it might be SSL related but I thought it was my own config.  Thanks for the help.
